### ISSUE TITLE
License in "blank"

### ISSUE THREAD

**Issue by RoinujNosde** [ReaperSoon/JailWorker#1]
https://github.com/ReaperSoon/JailWorker/blob/f992e1365b25f68946d8968739b2806e4277ec60/LICENSE#L634-L635
https://github.com/ReaperSoon/JailWorker/blob/f992e1365b25f68946d8968739b2806e4277ec60/LICENSE#L655

Should not you rewrite the lines above?

**Comment by stevecohenfr** [comment]
Haha yes, well spotted. Thx
